---
on: "push"

jobs:
        analysis:
                runs-on: "ubuntu-latest"
                name: "Code analysis"
                steps:
                        - uses: "actions/checkout@v3"
                        - name: "Black (code formatting)"
                          uses: "./.github/actions/black"
                          with:
                                  path: "onionpad"
                        - name: "PyLint"
                          uses: "./.github/actions/pylint"
                          with:
                                  path: "onionpad"
...
