---
on: "push"

jobs:
        analysis:
                runs-on: "ubuntu-latest"
                name: "Code analysis"
                steps:
                        - uses: "actions/checkout@v3"
                        - name: "Setup Python"
                          uses: "actions/setup-python@v4"
                          with:
                                  python-version: "3.11"
                        - name: "Install dependencies"
                          run: |
                                  python -m pip install --upgrade pip
                                  pip install \
                                      Adafruit-Blinka \
                                      adafruit-blinka-displayio \
                                      adafruit-circuitpython-display-shapes \
                                      adafruit-circuitpython-macropad \
                                      black \
                                      circuitpython-stubs \
                                      mypy \
                                      pylint
                        - name: "Black (code formatting)"
                          run: "black --check onionpad"
                        - name: "PyLint"
                          run: "pylint onionpad"
...
